# Generated by Django 2.2.14 on 2021-06-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0003_auto_20210604_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
