# Generated by Django 2.2.14 on 2021-06-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boec', '0004_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
